services:
  mysql:
    image: mysql:8.0
    container_name: mysql  # Set your custom container name here
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onebkk
      MYSQL_USER: onebkk
      MYSQL_PASSWORD: onebkk
    ports:
      - "3307:3306"  # Map container's port 3306 to host's port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    #privileged: true

  springboot:
    image: zaymmm/onebkk-api:p80
    container_name: onebkk-mw  # Set your custom container name here
    depends_on:
      - mysql
    ports:
      - "8080:8080" # Map container's port 8080 to host's port 8090
    #environment:
      #SPRING_JDBC_HOST: 127.0.0.1
      #SPRING_DATASOURCE_NAME: jdbc:mysql://127.0.0.1:3306/onebkk
      #SPRING_DATASOURCE_USERNAME: onebkk
      #SPRING_DATASOURCE_PASSWORD: onebkk
      #SPRING_JDBC_PORT: 3306
    #volumes:
      #- /root/app/onebkk/logs:/root/app/onebkk/logs  # Map container's /home/app/logs to a host directory
    #privileged: true

volumes:
  mysql_data:
